version: '3.8'

services:
  cars-app:
    container_name: cars-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/root/.ssh
      - ./startup.sh:/docker-entrypoint-initdb.d/startup.sh
    command: bash -c "/docker-entrypoint-initdb.d/startup.sh && sleep infinity"
    ports:
      - 5000:5000
    networks:
      - cars-network
    links:
      - cars-postgres
      - cars-pgadmin4

  cars-postgres:
    container_name: cars-postgres
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - cars-postgres-data:/var/lib/postgresql/data
      - ./createdbs.sh:/docker-entrypoint-initdb.d/createdbs.sh
    environment:
      POSTGRES_PASSWORD: carssecretpassword
      POSTGRES_USER: cars
      POSTGRES_DB: postgres
      POSTGRES_DATABASES: cars_db
    ports:
      - 5432:5432
    networks:
      - cars-network
  
  cars-pgadmin4:
    container_name: cars-pgadmin4
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    volumes:
      - cars-pgadmin4-data:/var/lib/pgadmin4/data
    environment:
      PGADMIN_DEFAULT_EMAIL: cars@admin.com
      PGADMIN_DEFAULT_PASSWORD: carsadmin
      MAX_LOGIN_ATTEMPTS: 5
    ports:
      - 4001:4001
      - 4002:4002
    networks:
      - cars-network

volumes:
  cars-postgres-data:
  cars-pgadmin4-data:

networks:
  cars-network:
    driver: bridge